system:
    seed: 0
    device: 0
data:
    directory: data
    label:
        filepath: label.csv
        x_col: filename
        y_col: class
        class_mode: categorical
    input_shape:
        height: 224
        width: 224
        depth: 3
    classes:
        - cat
        - dog
    split_size:
        training: 0.6
        validation: 0.2
        test: 0.2
model:
    name: ResNet50
    activation: softmax
    loss: categorical_crossentropy
    optimizer:
        name: Adam
        lr: 0.0001
    metrics:
        - accuracy
fitting:
    batch_size: 128
    epochs: 200
    verbose: 1
    log:
        directory: logs
    callbacks:
        ModelCheckpoint:
            filepath: model.h5
            monitor: val_loss
            verbose: 1
            save_best_only: true
        EarlyStopping:
            monitor: val_loss
            min_delta: 0.0001
            patience: 20
            verbose: 1
            restore_best_weights: true
        ReduceLROnPlateau:
            monitor: val_loss
            factor: 0.5
            patience: 5
            verbose: 1
            min_lr: 0.00001
