data:
    image_directory:
        training: ../data/JPEGImages/
        test:
    label_directory: ../data/Annotations/
    input_shape:
        height: 480
        width: 480
        depth: 3
    classes: # list
    batch_size: 16
model:
    backbone: ResNet50
    optimizer:
        name: Adam
        lr: 0.0001
    metrics: # https://keras.io/metrics/
fitting:
    epochs: 200
    verbose: 1
    callbacks:
        ModelCheckpoint:
            filepath: ../model/model.h5
            monitor: val_loss
            verbose: 1
            save_best_only: true
        EarlyStopping:
            monitor: val_loss
            min_delta: 0.0001
            patience: 20
            verbose: 1
            restore_best_weights: true
        ReduceLROnPlateau:
            monitor: val_loss
            factor: 0.5
            patience: 5
            verbose: 1
            min_lr: 0.00001
evaluation:
    verbose: 1
    filepath: ../out/out.csv
