data:
    directory:
        training: ../data/
        test: ../data/
    label:
        filepath: ../data/label.csv
        x_col: filename
        y_col: label
        class_mode: # https://keras.io/preprocessing/image/
    input_shape:
        height: 224
        width: 224
        depth: 3
    classes: # list
    split_size:
        training: 0.8
        test: 0.2
    batch_size: 128
model:
    backbone: # https://keras.io/applications/
    activation: # https://keras.io/activations/
    loss: # https://keras.io/losses/
    optimizer:
        name: Adam
        lr: 0.0001
    metrics: # https://keras.io/metrics/
fitting:
    epochs: 200
    verbose: 1
    callbacks:
        ModelCheckpoint:
            filepath: ../model/model.h5
            monitor: val_loss
            verbose: 1
            save_best_only: true
        EarlyStopping:
            monitor: val_loss
            min_delta: 0.0001
            patience: 20
            verbose: 1
            restore_best_weights: true
        ReduceLROnPlateau:
            monitor: val_loss
            factor: 0.5
            patience: 5
            verbose: 1
            min_lr: 0.00001
evaluation:
    verbose: 1
    filepath: ../out/out.csv
